In [4]:
import cv2
import numpy as np

In [5]:
img = cv2.imread('data/book.png')
img_hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV) #转换到hsv空间
#print(img.shape)
src = []
def mouse_event(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDBLCLK:   #双击左键显示图像的坐标和对应的rgb值
        print('img pixel value at(', x, ',', y, '):',img[y, x])  #坐标(x,y)对应的像素值应该是img[y,x]
        text = '(' + str(x) + ',' + str(y) + ')' + str(img[y,x])
        cv2.putText(img,text,(x,y),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0),1)  #绘制文字
        src.append([x,y])
    if event == cv2.EVENT_RBUTTONDBLCLK:   #双击右键显示图像的坐标和对应的hsv值
        print('img_hsv pixel value at(', x, ',', y, '):',img_hsv[y, x])  #坐标(x,y)对应的像素值应该是img_hsv[y,x]
        text = '(' + str(x) + ',' + str(y) + ')' + str(img_hsv[y,x])
        cv2.putText(img,text,(x,y),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1)  #绘制文字
cv2.namedWindow('image',cv2.WINDOW_NORMAL)  #定义窗口
#cv2.resizeWindow('image',(800,800))
   
cv2.setMouseCallback('image',mouse_event)  #鼠标回调
  
while True:
    cv2.imshow('image',img)
    if cv2.waitKey(1)==ord('q'):
        break
  
cv2.destroyAllWindows()
print(src)

img pixel value at( 624 , 61 ): [94 84 86]
img pixel value at( 100 , 332 ): [75 55 73]
img pixel value at( 398 , 590 ): [16 17 51]
img pixel value at( 927 , 273 ): [98 98 98]
[[624, 61], [100, 332], [398, 590], [927, 273]]


In [6]:
img_book = cv2.imread('data/book.png')
h,w,c =img_book.shape
src = np.float32(src) #用微信截图来确定roi区域的四个角的坐标点位置(或者用鼠标事件输出四角坐标)
# dst = np.float32([[300,200],[300,500],[510,500],[510,200]]) 
dst = np.float32([[0,0],[0,250],[250,250],[250,0]])  #只保留roi区域，warpPerspective函数中尺寸设置为roi的宽高

M = cv2.getPerspectiveTransform(src,dst) #透视变换矩阵
print(M)
 
# new_book = cv2.warpPerspective(img_book,M,(w,h)) #透视变换  二维平面获得接近三维物体的视觉效果的算法
new = cv2.warpPerspective(img,M,(210,300)) #透视变换  变换后的roi区域的宽高，只保留roi区域
  
cv2.imshow('img_book',img)
cv2.imshow('new_book',new)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 3.78018138e-01  7.30928060e-01 -2.80469930e+02]
 [-3.06728251e-01  4.38389905e-01  1.64656644e+02]
 [-2.26586927e-05  3.62599217e-04  1.00000000e+00]]
